"""Schema creation

Revision ID: 02c52ab1e43d
Revises: 
Create Date: 2026-04-30 08:57:48.882328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c52ab1e43d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_essential', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('payment_method',
    sa.Column('id_method', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_method')
    )
    op.create_table('tag',
    sa.Column('id_tag', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id_tag'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction_type',
    sa.Column('id_type', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_type')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('budget',
    sa.Column('id_budget', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_budget')
    )
    op.create_table('financial_profile',
    sa.Column('id_profile', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('savings_goal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='eur', nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_profile'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('budget_category',
    sa.Column('id_budget', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=5, scale=2), server_default='0.80', nullable=False),
    sa.ForeignKeyConstraint(['id_budget'], ['budget.id_budget'], ),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], ),
    sa.PrimaryKeyConstraint('id_budget', 'id_category')
    )
    op.create_table('transactions',
    sa.Column('id_transaction', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_budget', sa.Integer(), nullable=True),
    sa.Column('id_method', sa.Integer(), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_budget'], ['budget.id_budget'], ),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], ),
    sa.ForeignKeyConstraint(['id_method'], ['payment_method.id_method'], ),
    sa.ForeignKeyConstraint(['id_type'], ['transaction_type.id_type'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_table('transaction_tag',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id_tag'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_transaction', 'id_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tag')
    op.drop_table('transactions')
    op.drop_table('budget_category')
    op.drop_table('financial_profile')
    op.drop_table('budget')
    op.drop_table('users')
    op.drop_table('transaction_type')
    op.drop_table('tag')
    op.drop_table('payment_method')
    op.drop_table('category')
    # ### end Alembic commands ###
