"""Added last_update attribute

Revision ID: 239edc94cb72
Revises: 02c52ab1e43d
Create Date: 2026-04-30 19:48:51.986326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239edc94cb72'
down_revision: Union[str, Sequence[str], None] = '02c52ab1e43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('budget_category', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('category', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('financial_profile', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('payment_method', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('tag', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('transaction_type', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('transactions', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('users', sa.Column('last_update', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_update')
    op.drop_column('transactions', 'last_update')
    op.drop_column('transaction_type', 'last_update')
    op.drop_column('tag', 'last_update')
    op.drop_column('payment_method', 'last_update')
    op.drop_column('financial_profile', 'last_update')
    op.drop_column('category', 'last_update')
    op.drop_column('budget_category', 'last_update')
    op.drop_column('budget', 'last_update')
    # ### end Alembic commands ###
